### ISSUE TITLE
App responsible for search on App Screen

### ISSUE THREAD

**Issue by Trippak** [invinciblevenom/debloat_samsung_android#18] opened 2024-09-29 10:42 UTC
I want to return the application search, I searched for the package, but did not find it.

**Comment by invinciblevenom** [comment] 2024-09-29 12:55
Run this in cmd
`adb shell cmd package install-existing --user 0 com.samsung.android.app.galaxyfinder`

**Comment by invinciblevenom** [comment] 2024-09-29 12:57
Close the issue if the problem is resolved. Thanks!

**Closed as completed** 2024-09-30 12:00 UTC
